# Generated by Django 2.1.7 on 2019-03-22 10:09

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('content', models.TextField()),
                ('seo_title', models.CharField(max_length=250)),
                ('seo_description', models.CharField(max_length=160)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publisher', 'Publisher')], default='Draft', max_length=9)),
                ('auther', models.ForeignKey(on_delete='s', related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
